boostcampwm2023/web12-algo-with-me

- be/algo-with-me-api/.gitignore
- be/algo-with-me-api/package.json
- be/algo-with-me-api/pnpm-lock.yaml
- be/algo-with-me-api/src/app.module.ts
typeorm을 설치해서 db와 연동하였습니다.
db 유저 생성 및 db 생성을 완료했습니다.
> feat: typeorm 연동, db 연동

- README.md
문서 링크 카테고라이징 (소제목 추가)
개발 스택 문서 추가
> chore: README 업데이트

- .github/workflows/main.yml
- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/vite.config.ts
한 일
- gp-pages 설치
- 관련 script 추가
- 관련 vite config 추가
- github action을 위한 yml 파일 추가
- gp-pages로 배포한 결과로 무한 Loading 걸리는 게 맞습니다.
- msw가 dev 모드일 때만 request 가로채도록 설계되어있음.
관련 링크
아래 링크에 자세하게 나와 있습니다.
https://www.notion.so/github-action-b4c2ca039b494019ad2ce9ef344ba2f7
> [#47] fe cicd 작업 추가

- .github/workflows/main.yml
- 참고 https://stackoverflow.com/questions/60710209/trigger-github-actions-only-when-pr-is-merged
> [#56] FE CI/CD main.yml 파일 수정

- be/algo-with-me-api/package.json
- be/algo-with-me-api/pnpm-lock.yaml
- be/algo-with-me-api/src/competition/controllers/competition.controller.ts
- be/algo-with-me-api/src/competition/controllers/problem.controller.ts
- be/algo-with-me-api/src/competition/dto/competition.problem.response.dto.ts
- be/algo-with-me-api/src/competition/dto/create-problem.dto.ts
- be/algo-with-me-api/src/competition/dto/problem.list.response.dto.ts
- be/algo-with-me-api/src/competition/dto/problem.response.dto.ts
- be/algo-with-me-api/src/competition/dto/score-result.dto.ts
- be/algo-with-me-api/src/competition/entities/problem.entity.ts
- be/algo-with-me-api/src/competition/services/competition.service.ts
- be/algo-with-me-api/src/competition/services/problem.service.ts
- be/algo-with-me-api/src/main.ts
swagger 설치 및 적용했습니다.
- response를 swagger에 명시하기 위해 dto를 추가했습니다. 생성자 인자가 굉장히 많은데 다른 방법이 없나 모르겠네요. dto 이름 도 임의로 정했는데 괜찮을까요?
- swagger 설정을 했습니다.
- api 별 요청, 응답이 무엇인지 기술하고, api 설명을 추가했습니다.
> swagger 설치 및 적용

- be/algo-with-me-api/src/competition/controllers/competition.controller.ts
- be/algo-with-me-api/src/competition/dto/competition.response.dto.ts
- be/algo-with-me-api/src/competition/dto/create-competition.dto.ts
- be/algo-with-me-api/src/competition/dto/update-competition.dto.ts
- be/algo-with-me-api/src/competition/services/competition.service.ts
- be/algo-with-me-api/src/competition/services/problem.service.ts
운영서버에 배포된 환경에서도 api 서버가 잘 동작하도록 한다.
기타 competition api의 버그를 고쳤다.
approve해주시면 바로 수정한 내용 배포해서 프론트 분들 바로 쓰게 해드릴 생각입니다.
> [#74] 백엔드 통합 - api 서버

- be/algo-with-me-api/src/app.module.ts
- be/algo-with-me-api/src/auth/auth.strategy.ts
- be/algo-with-me-api/src/auth/controllers/auth.controller.ts
- be/algo-with-me-api/src/competition/controllers/competition.controller.ts
- be/algo-with-me-api/src/competition/dto/create-competition.dto.ts
- be/algo-with-me-api/src/competition/entities/competition.entity.ts
- be/algo-with-me-api/src/competition/entities/competition.problem.entity.ts
- be/algo-with-me-api/src/competition/entities/submission.entity.ts
- be/algo-with-me-api/src/user/decorators/user.decorators.ts
- be/algo-with-me-api/src/user/dto/user.response.dto.ts
- be/algo-with-me-api/src/user/entities/user.entity.ts
- 유저 - 제출 관계 생성
- 유저 - 대회 관계 생성
- 대회 - 제출 관계 수정
- user 가져오기 위한 데코레이터 구현
> [#57] 유저 대회 구현을 완료하면 db dto 등을 그에 맞춰 변경하기

- be/algo-with-me-api/src/auth/auth.strategy.ts
- be/algo-with-me-api/src/competition/controllers/competition.controller.ts
- be/algo-with-me-api/src/competition/dto/create-competition.dto.ts
- be/algo-with-me-api/src/competition/dto/update-competition.dto.ts
- be/algo-with-me-api/src/competition/services/competition.service.ts
- be/algo-with-me-api/src/user/services/user.service.ts
- 대회 생성시 유저정보 추가
- 대회 수정시 수정 요청자가 대회 주최자가 맞는지 확인
> [#109] 유저 대회 구현에 따른 대회 생성 수정 기능 수정

- frontend/src/hooks/competition/useCompetition.ts
소켓 통신 양식 변경에 따라 Bearer 문자열을 추가했습니다.
https://www.notion.so/websocket-8ab0814b081a4f57994818de4c3b9a68?pvs=4
> [#000] 소켓의 auth 토큰에 Bearer 추가

- be/algo-with-me-docker/Dockerfile
- be/algo-with-me-docker/node-sh/run.sh
- be/algo-with-me-docker/node-sh/runJs.sh
- be/algo-with-me-score/src/score/services/score.service.ts
코드가 정말 짧아서 별로 안한 것 같지만 아래 제 똥꼬쇼를 봐주세요.
https://www.notion.so/A-B-84cd187171d840d6a8e4b1838cf7194b?pvs=4
https://www.notion.so/019fa83362f74ce9b9856cb0b36b4de4?pvs=4
세줄 요약
- 코드 실행 시간, 메모리 측정해서 이제 API 서버에 전달해줌 (timeUsage, memoryUsage)
- A+B 문제에서 정답 코드를 제출해도 오답 처리하는 버그 해결
- 메모리 (최대) 사용량을 측정할 때, 테스트케이스 및 결과파일을 읽고 쓰는 동작에 사용되는 메모리까지 측정하기 때문에 메모리를 적게 사용하는 문제의 경우 측정값이 원래보다 다소 높을 수 있음
> [#73] 채점용 docker image 기능 확장

- be/build-api
- be/build-docker
- be/build-score
- be/run-api
- be/run-docker
- be/run-score
> [#152] build run docker 쉘스크립트

- frontend/src/apis/problems/types.ts
- frontend/src/components/Simulation/SimulationInputModal.tsx
- frontend/src/hooks/problem/useCompetitionProblem.ts
- frontend/src/hooks/simulation/useSimulation.ts
- frontend/src/pages/CompetitionPage.tsx
테스트 추가 삭제가 테스트 출력 화면에 반영되지 않는 문제 해결
> [#163] 시뮬레이션 모달 확인 클릭시 동작 안하는 버그

- .github/workflows/main.yml
- 자동 배포 스크립트를 작성했습니다.
- 실제 잘 동작하는지 테스트가 필요합니다.
- be-dev로 push 될 때마다, 스크립트가 동작합니다.
- 모든 서버가 내려갔다 올라갑니다.
> [#187] 자동 배포 구현

- be/algo-with-me-api/src/competition/controllers/competition.controller.ts
- be/algo-with-me-api/src/competition/dto/competition.is.joinable.dto.ts
- be/algo-with-me-api/src/competition/gateways/competition.gateway.ts
- be/algo-with-me-api/src/competition/services/competition.service.ts
- 유저가 대회에 입장 가능한지 검증하는 api 입니다.
- 대회 진행중인지 아닌지 확인합니다.
- 대회에 참여중인 유저인지 확인합니다.
> [#197] 유저가 대회 참여가 가능한 상태인지 검증하는 api 구현

- frontend/src/components/Problem/ProblemSolveContainer.tsx
- frontend/src/components/Simulation/SimulationResultList.tsx
일부 리팩토링 (시뮬|제출 탭 전환 부 상수화)
시뮬레이션 결과를 비교해서 일치하면 체크, 아니면 x 표시 출력
시뮬레이션 결과가 일치하면 체크, 아니면 X 표시 출력
만약 새 테스트케이스가 추가되면 결과 초기화
> [#229] 테스트케이스 expected값 비교

- frontend/panda.config.ts
- frontend/src/apis/problems/index.ts
- frontend/src/apis/problems/types.ts
- frontend/src/components/Common/Card/Card.tsx
- frontend/src/components/Common/Card/index.ts
- frontend/src/components/Common/Chip.tsx
- frontend/src/components/Common/Link.tsx
- frontend/src/components/Common/index.ts
- frontend/src/components/CompetitionDetail/AfterCompetition.tsx
- frontend/src/components/CompetitionDetail/BeforeCompetition.tsx
- frontend/src/components/CompetitionDetail/Card.tsx
- frontend/src/components/CompetitionDetail/CompetitionDetailContent.tsx
- frontend/src/components/CompetitionDetail/CompetitionDetailInfo.tsx
- frontend/src/components/CompetitionDetail/CompetitionMembersInfo.tsx
- frontend/src/components/CompetitionDetail/DuringCompetition.tsx
- frontend/src/components/CompetitionDetail/styles/styles.ts
- frontend/src/components/Layout/PageLayout.tsx
- frontend/src/components/Main/Buttons/GoToCreateCompetitionLink.tsx
- frontend/src/constants/index.ts
- frontend/src/pages/CompetitionDetailPage.tsx
- frontend/src/pages/MainPage.tsx
- frontend/src/pages/ProblemPage.tsx
- frontend/src/utils/type/index.ts
- 대회 생성하기 버튼이 아니라 버튼 안의 텍스트를 눌러야 링크 이동했던 것을 수정 
- 메인 페이지 Alog With Me -> Algo With Me로 수정
- chip 디자인 수정
- 대회 상세 페이지 참여인원/ 최대 참여인원 추가
- 대회 상세 페이지 시작 시간, 종료 시간 추가
- 문제 상세 보기 페이지 api 수정
- https://www.notion.so/1-4c1c78b356e44db19e09fec4821a504b?pvs=4
> [#234] 1차 데모 버그 픽스

- frontend/src/components/Simulation/SimulationResultList.tsx
- frontend/src/hooks/simulation/types.ts
- frontend/src/hooks/simulation/useSimulation.ts
- frontend/src/modules/evaluator/EvalTaskManager.ts
- frontend/src/modules/evaluator/index.ts
- frontend/src/modules/evaluator/quickjs.ts
- frontend/src/modules/evaluator/types.ts
> [#240] 시뮬레이터에 console 추가하기

- frontend/src/index.css
> [#244] 폰트 적용하기

- frontend/src/components/Common/Socket/SocketProvider.tsx
- 웹 소켓을 싱글톤으로 사용하고 있는데, React.StrcitMode에서 에러가 발생함
- build 상에서 unmounted할 때 소켓을 끊으면 문제가 없기 때문에 unmounted할 때 소켓을 끊기로 결정함
https://github.com/boostcampwm2023/web12-algo-with-me/assets/78193416/3435359a-2c4b-4fdd-ad9b-73dbd939db2f
> [#242] websocket 관련 버그 제거

- frontend/src/apis/joinCompetition/index.ts
- frontend/src/apis/joinCompetition/types.ts
- frontend/src/components/Common/Button.tsx
- frontend/src/components/CompetitionDetail/Buttons/EnterCompetitionButton.tsx
- frontend/src/components/Dashboard/DashboardModal.tsx
- frontend/src/components/Dashboard/DashboardTable.tsx
- frontend/src/components/Main/Buttons/GoToCreateCompetitionLink.tsx
- frontend/src/components/Main/Buttons/ViewDashboardButton.tsx
- frontend/src/components/Main/CompetitionTable.tsx
- frontend/src/components/Problem/ProblemSolveContainer.tsx
- frontend/src/constants/index.ts
- frontend/src/main.tsx
- frontend/src/pages/CompetitionPage.tsx
- frontend/src/pages/CreateCompetitionPage.tsx
- frontend/src/router.tsx
- frontend/src/utils/date/index.ts
> [#257] 1차 데모 버그 픽스 2

- be/algo-with-me-api/src/competition/services/competition.service.ts
- be/algo-with-me-api/src/dashboard/dashboard.service.ts
- 점수 계산을 분 단위에서 초 단위로 변경합니다.
- 채점 결과 stdout을 클라이언트에게 보내지 않도록 수정합니다.
- 문제에 대한 채점이 완료되면 websocket을 통해 완료되었다는 메시지를 전송합니다.
- 로그를 하나 추가했습니다.
> [#262] 1차 코딩 대회 이후 수정

- fe/src/components/Common/Socket/SocketProvider.tsx
웹소켓 재연결 시 발생하는 문제 해결
https://www.notion.so/React-StrictMode-e149eb5f6f1f40b58247da08aac3a9b0
> [#282] 개발 환경에서 websocket 재연결 문제 해결

- be/algo-with-me-api/src/competition/controllers/competition.controller.ts
- be/algo-with-me-api/src/competition/dto/create-submission.dto.ts
- be/algo-with-me-api/src/competition/gateways/competition.gateway.ts
- be/algo-with-me-api/src/problem/language.enums.ts
languageId를 createSubmissionDto의 toEntity()에 추가해주지 않아 생겼던 문제 해결.
> [#298] db 스키마 변경 이후 제출 불가 문제 해결

- fe/src/components/Common/Socket/SocketProvider.tsx
- fe/src/components/Problem/ProblemSolveContainer.tsx
- fe/src/components/Submission/SubmissionButton.tsx
- fe/src/hooks/competition/useCompetition.ts
- fe/src/hooks/simulation/useSimulation.ts
- 소켓 네임스페이스 통일화
- 제출 관련 프로퍼티 추가
> [#297] 언어추가, 소켓 네임스페이스 괸련 에러

- fe/src/hooks/editor/useUserCode.ts
- 대회 페이지 리로드 시 undefined 을 참조하는 에러 발생
- 예외처리
> [301] 대회 페이지 리로드시 undefined 참조에러

- fe/src/components/Layout/SandboxLayout.tsx
- fe/src/components/Problem/ProblemSolveContainer.tsx
- fe/src/components/Sandbox/SandboxProblemContainer.tsx
- fe/src/components/Sandbox/SandboxSubmissionButton.tsx
- fe/src/components/Sandbox/SandboxSubmissionResult.tsx
- fe/src/components/Sandbox/index.tsx
- fe/src/components/Sandbox/sandbox.problem.info.ts
- fe/src/components/Simulation/SimulationExecButton.tsx
- fe/src/hooks/simulation/types.ts
- fe/src/hooks/simulation/useSimulation.ts
- fe/src/modules/evaluator/EvalTaskManager.ts
- fe/src/modules/evaluator/eval.worker.ts
- fe/src/modules/evaluator/quickjs.ts
- fe/src/modules/evaluator/types.ts
- fe/src/pages/SandboxPage.tsx
- QuickJS 런타임 시에 사용한 메모리 계산하는 로직 추가
- 둘러보기 (샌드박스) 페이지 코드 평가 프론트에서 실행
- https://www.notion.so/QuickJS-memory-4a8e5b4047af48d29560fb69b8d07322
> [#303] 둘러보기 페이지 기능추가
