boostcampwm2023/web12-algo-with-me

be/algo-with-me-api/src/competition/competition.controller.ts, be/algo-with-me-api/src/competition/competition.module.ts, be/algo-with-me-api/src/competition/competition.service.ts, be/algo-with-me-api/src/competition/dto/create-problem.dto.ts, be/algo-with-me-api/src/competition/entities/problem.entity.ts
- 대회 문제용 api 구현했습니다. 사용자 에디터에 보여줄 솔루션 함수가 포함된 코드, 공개된 테스트 케이스가 기존 문제용 api에 추가로 들어갑니다.
- console.log 삭제했습니다.
- 파일 못찾을 시 예외처리 해주었습니다.
- 문제 엔티티에서 solutionCode를 추가해주었습니다.
=> feat: 대회 문제용 api 구현, consle.log 삭제, 파일 없을 시 예외처리, solutionCode 컬럼 추가

frontend/.eslintrc.cjs, frontend/src/App.css, frontend/src/components/ContestPage.tsx, frontend/src/components/Editor.tsx, frontend/src/components/Tester.tsx, frontend/src/modules/evaluator/eval.worker.ts, frontend/src/modules/evaluator/evalCode.ts, frontend/src/modules/evaluator/index.ts, frontend/src/modules/evaluator/types.ts
- web worker 1개가 추가되었으며 이를 통해 입력된 코드를 수행할 수 있습니다.
- 일단 eval을 사용하도록 구현하였으며 다음 스프린트를 통해 QuickJS로 교체할 예정입니다.
- @style이 import의 최상위에 오도록 lint 규칙을 변경했습니다.
- [결정 참고](https://boostcampwm-8-me.slack.com/archives/C0615MFR0V7/p1700103597517249) 
- eslint에 `'space-before-function-paren':'off'`를 추가했습니다.  
- prettier와의 중복으로 인해 아래의 충돌 현상이 있었고, 이를 위해 lint의 규칙을 껐습니다. 
- index.css에서 모든 텍스트를 중앙정렬하는 옵션이 있었는데 이 때문에 codemirror도 중앙정렬이 되는 문제가 있어 제거했습니다.
```ts
// space before function paren 옵션은 function 이름과 파라미터 사이에 공백을 넣도록 하는 옵션입니다.
// 이는 prettier에서 공백을 빼는 규칙과 충돌하여 껐습니다.
function something() { // 여기서 something 다음에 공백을 넣도록 강제하는 옵션을 끔
// ...
}
```
코드를 입력하고 파라미터를 넣으면 코드를 수행할 수 있습니다.
=> [#23] 웹 워커 추가 & 코드 실행 환경 구성

be/algo-with-me-api/src/competition/competition.enums.ts, be/algo-with-me-api/src/competition/controllers/competition.controller.ts, be/algo-with-me-api/src/competition/dto/score-result.dto.ts, be/algo-with-me-api/src/competition/entities/submission.entity.ts, be/algo-with-me-api/src/competition/gateways/competition.gateway.ts, be/algo-with-me-api/src/competition/services/competition.service.ts
- redis queue에 들어가는 데이터에 socketId를 추가했습니다.
- 
- 채점 서버에서 테스트 케이스 채점 완료시 호출할 api를 구현하였습니다.
- submission entity의 json 기본 값을 []로 했습니다.
- 채점 결과를 db에 저장합니다.
- 채점 결과를 websocket을 통해 client에게 전송합니다.
- 서비스 로직에서 socket 정보를 갖고 있게 하기 위해 CompetitionGateWay에 afterInit메서드를 구현하였습니다.
- 테스트용으로 사용했던 코드를 주석 처리했습니다. 추후 참고하려고 놔두었는데, 필요없다고 판단되면 추후 삭제하겠습니다.
- 유저, 대회가 구현이 안되서 나중에 추가해야 될 것들을 todo로 작성해놨습니다.
=> api 서버에서 채점 결과 받아서 client에게 전송하는 것 구현

be/algo-with-me-api/src/app.module.ts, be/algo-with-me-api/src/competition/competition.module.ts, be/algo-with-me-api/src/competition/controllers/competition.controller.ts, be/algo-with-me-api/src/competition/dto/competition.response.dto.ts, be/algo-with-me-api/src/competition/dto/create-competition.dto.ts, be/algo-with-me-api/src/competition/dto/update-competition.dto.ts, be/algo-with-me-api/src/competition/entities/competition.entity.ts, be/algo-with-me-api/src/competition/entities/problem.entity.ts, be/algo-with-me-api/src/competition/entities/submission.entity.ts, be/algo-with-me-api/src/competition/services/competition.service.ts
대회 정보 API 작성했습니다. (delete 제외, CRU)
User 엔티티가 만들어지면, 다음 작업들이 필요합니다
1. User와 Competition과의 관계 설정
2. API 반환값 일부 변경 (userId(대회 출제자의 id)까지 반환)
=> [#59] 대회 정보 api - create read update 구현

frontend/src/components/Contest/ContestBreadCrumb.tsx, frontend/src/pages/ProblemPage.tsx, frontend/src/router.tsx
- ContestBreadCrumb에서 key props를 추가하는 로직을 추가했습니다.
- 문제 보기 페이지인 ProblemPage를 작성하였습니다.
- **TODO**: api를 적용하는 태스크를 진행하며 수정할 계획입니다.
=> [#85] 문제 보기

be/algo-with-me-api/src/app.module.ts, be/algo-with-me-api/src/competition/competition.module.ts, be/algo-with-me-api/src/competition/controllers/competition.controller.ts, be/algo-with-me-api/src/competition/controllers/problem.controller.ts, be/algo-with-me-api/src/competition/dto/problem.simple.response.dto.ts, be/algo-with-me-api/src/competition/entities/competition.entity.ts, be/algo-with-me-api/src/competition/entities/competition.problem.entity.ts, be/algo-with-me-api/src/competition/entities/problem.entity.ts, be/algo-with-me-api/src/competition/services/competition.service.ts, be/algo-with-me-api/src/competition/services/problem.service.ts
resolved #90 
- 대회별 문제 목록 조회 api 구현
- 다대다 데코레이터를 없애고 중간 테이블 엔티티를 구현하였습니다.
- join을 줄이고 select 되는 컬럼들을 줄여보려고 했습니다. 결과적으로 두번의 조인이 발생합니다.
- typeorm 쿼리 로그를 출력하도록 수정했습니다.
- 그냥 id를 사용하던 것을 어떤 id인지 구분하기 쉽게 변수명을 수정했습니다.
https://www.notion.so/api-d479ad4a28df4e72b98b4952a1a3fbac?pvs=4
=> [#90] 대회별 문제 목록 조회 api 구현

frontend/src/hooks/competition/useCompetition.ts, frontend/src/hooks/problem/useProblem.ts, frontend/src/pages/ContestPage.tsx, frontend/src/pages/ProblemPage.tsx, frontend/src/router.tsx
- 대회 화면 페이지와 문제 보기 페이지에서 실제 api를 받아 대회와 문제에 대한 정보를 처리하도록 코드를 작성하였습니다.
- 대회 화면 페이지에 대해 라우터를 수정해서 대회 id에 따라 화면을 출력하도록 코드를 수정하였습니다.
- 대회 정보 api 안에 해당 대회에 어떠한 정보가 들어있는지에 대한 응답 데이터가 없어서, BE에서 이를 처리해주면 코드를 수정해야 합니다.
- 현재 ContestPage안에서 useEffect를 두 개로 나눠서 사용하고 있는데, 이렇게 하는 게 좋은 방법인지 궁금합니다!
=> [#91] 문제 보기 api 연동

be/algo-with-me-api/src/auth/controllers/auth.controller.ts
- 깃허브 로그인 완료되고 나서 서버 url로 이동하던 것을 프론트의 url로 리다이렉트 되도록 수정했습니다.
=> [#95] 깃허브 로그인 완료시 프론트 url로 리디렉션 되도록 수정

be/algo-with-me-api/src/competition/controllers/competition.controller.ts, be/algo-with-me-api/src/competition/dto/competition.response.dto.ts, be/algo-with-me-api/src/competition/dto/competition.simple-response.dto.ts, be/algo-with-me-api/src/competition/dto/create-competition.dto.ts, be/algo-with-me-api/src/competition/services/competition.service.ts
- 대회 전체 조회 API 구현했습니다.
- 대회 생성 API에서, 대회에 사용되는 문제 리스트를 입력으로 받도록 했습니다. (problems: number[])
바로 배포할 계획입니다.
=> [#94] 대회 조회/생성 api 수정

frontend/index.html, frontend/src/components/Login/index.tsx, frontend/src/components/Problem/Markdown.tsx, frontend/src/components/submissionResult/ResultList.tsx, frontend/src/pages/LoginPage.tsx, frontend/src/router.tsx, frontend/vite.config.ts
- fe-dev를 rebase하는 과정에서 타인의 코드가 섞이는 문제가 발생해서 최신 fe-dev에서 새로운 브랜치를 하나 팠습니다. 
- 이전 브랜치 
https://github.com/boostcampwm2023/web12-algo-with-me/compare/fe-dev...99-%EB%A1%9C%EA%B7%B8%EC%9D%B8-%ED%8E%98%EC%9D%B4%EC%A7%80-%EA%B5%AC%ED%98%84
- 로그인 페이지 구현
- 배포위한 vite 설정 추가
- 라우팅 작업
- build 시에 발생하는 타입에러 수정
- accessToken 저장 로직은 [#69]의 브랜치 코드 그대로 main page가 생기면 추가하겠습니다.
- 위의 작업은 commons header 작업을 할 때 수행됩니다.
=> [#99] 로그인 페이지 구현

be/algo-with-me-api/src/app.module.ts, be/algo-with-me-api/src/competition/competition.module.ts, be/algo-with-me-api/src/competition/controllers/competition.controller.ts, be/algo-with-me-api/src/competition/dto/problem.response.dto.ts, be/algo-with-me-api/src/competition/entities/competition.entity.ts, be/algo-with-me-api/src/competition/entities/competition.participant.entity.ts, be/algo-with-me-api/src/competition/entities/competition.problem.entity.ts, be/algo-with-me-api/src/competition/entities/participant.entity.ts, be/algo-with-me-api/src/competition/entities/problem.entity.ts, be/algo-with-me-api/src/competition/entities/submission.entity.ts, be/algo-with-me-api/src/competition/services/competition.service.ts, be/algo-with-me-api/src/competition/services/problem.service.ts, be/algo-with-me-api/src/exception/exception.enum.ts, be/algo-with-me-api/src/exception/service.exception.filter.ts, be/algo-with-me-api/src/exception/service.exception.ts, be/algo-with-me-api/src/main.ts, be/algo-with-me-api/src/user/entities/user.entity.ts
- entity를 반환하던 service 로직을 dto를 반환하도록 수정했습니다.
- 대회 참여 api 구현했습니다.
- 유저-대회 엔티티를 competition 폴더에 생성했습니다.
- swagger 관련 수정
- entity는 client에게 보여질 일이 없으므로 엔티티에 붙어있는 swagger 데코레이터를 삭제했습니다.
- 대회 참여를 위해 유저 인증이 필요한데, swagger에서 토큰으로 인증할 수 있도록 하였습니다.
- service에서 발생하는 에러가 자꾸 내부 서버에러로 서버가 죽어버리는 문제가 발생했습니다.
- custom error handling을 해주어 문제를 해결하려고 시도했습니다.
- 알고보니 컨트롤러에서 service 로직을 호출하고 await을 하지 않아 filter에 걸리지 않아 에러를 처리하지 못하는 것으로 확인했습니다.
- custom error handling 코드는 추후 사용가능성이 있으므로 삭제하지 않고 사용하지 않는 상태로 놔두려고 합니다.
=> [#55] 대회 참여 api 구현, swagger, 에러핸들링

frontend/public/mockServiceWorker.js, frontend/src/components/Main/CompetitionList.tsx, frontend/src/components/Submission/SubmissionResult.tsx, frontend/src/components/Submission/types.ts, frontend/src/hooks/competition/useCompetition.ts, frontend/src/pages/ContestPage.tsx, frontend/src/router.tsx, frontend/vite.config.ts
소켓 로직 변경 (API가 변경됨)
대회 이동 link 추가
라우팅 base 제거 (netlify에서 배포하기 위함)
=> [#113] 소켓 로직 변경 적용

be/algo-with-me-api/src/competition/gateways/competition.gateway.ts, be/algo-with-me-api/src/competition/services/competition.service.ts
- scoreResult dto 스펠링 수정
- websocket을 통해 서버 시간 전송해주는 로직 구현
- 서버 시간은 클라이언트가 요청 했을 때만 보내주기로 하였습니다.
resolved #120
=> [#120] websocket 헬스 체크 구현

frontend/src/components/Common/Loading.tsx, frontend/src/components/SocketTimer/index.tsx, frontend/src/hooks/timer/useSocketTimer.ts, frontend/src/pages/ContestPage.tsx
- mockWebSocket => 실제 webSocket으로 변경
- 필요업는 코드 삭제
- loading component에 - 들어간  프로퍼티 네임 카멜 케이즈로 변경
- 웹 소켓 끊겼다가 다시 연결 되어도 타이머 정상 작동하는지 체크
- <React.StrictMode>를 off하고 했습니다. 
https://github.com/boostcampwm2023/web12-algo-with-me/assets/78193416/3e265cea-f853-4d92-b14a-2782ecdbd968
=> [#79] 웹 소켓 정상작동 시에 연결

frontend/src/apis/competitions/types.ts, frontend/src/components/Common/Logo.tsx, frontend/src/components/CompetitionDetail/AfterCompetition.tsx, frontend/src/components/CompetitionDetail/BeforeCompetition.tsx, frontend/src/components/CompetitionDetail/CompetitionMembersInfo.tsx, frontend/src/components/CompetitionDetail/DuringCompetition.tsx, frontend/src/hooks/competition/useCompetition.ts
대회 세부정보 페이지에서 대회 생성자와 참여자를 보여줍니다.
=> [#139] 대회 세부정보 페이지 추가 구현

frontend/src/components/Common/Modal/Modal.tsx, frontend/src/components/Simulation/SimulationInputList.tsx, frontend/src/components/Simulation/SimulationInputModal.tsx, frontend/src/hooks/simulation/types.ts, frontend/src/pages/ContestPage.tsx
- 테스트 케이스 추가하는 모달에 확인, 닫기, 삭제 버튼(로직) 구현
- 확인 버튼
-  인풋 검증 로직 체크 후 저장   
- 닫기 버튼
-  모달 창 열기전 테스트 케이스 반영.
- 테스트 케이스 삭제
- 그냥 삭제함
- 백엔드와 test case type에 대해서 논하고 타입 검증 로직 추가
https://github.com/boostcampwm2023/web12-algo-with-me/assets/78193416/cc19012c-0e64-4078-9c12-6b46c0693c51
- 버튼에 css 먹여도 index.css에서 온 애가 이기더라구요. 나중에 css 정리해야겠습니다.
=> [#129] 테스트 케이스 추가삭제 훅 생성

be/algo-with-me-api/src/competition/dto/competition.problem.response.dto.ts, be/algo-with-me-api/src/competition/services/competition.service.ts
https://www.notion.so/434b7c29f1f94f30b342f075843aa7e9
위 노션에 정리해둔 양식에 맞게 테스트케이스 값들을 보내줬습니다.
input, output 값을 JSON으로 변경하고 metadata 파일을 만들어줬기 때문에, 이제 프레임 코드 생성을 자동화할 수도 있습니다. 
배포 서버의 테스트케이스 파일, DB에 저장된 문제 프레임코드 변경해줬습니다.
`submissions/:problemId/metadata` 파일에 들어간 내용 예시
```json
{"input":[{"name":"times","type":"integer[][2]"}],"output":{"name":"maxMeetings","type":"integer"},"sampleTestcaseNum":1,"secretTestcaseNum":10}
```
예시: `/competitions/problems/1`
```json
{
"id": 1,
"title": "A+B",
"timeLimit": 2000,
"memoryLimit": 128000,
"content": "# A+B\n\n### 제한\n\n- 시간 제한: 2초\n- 메모리 제한: 128MB\n\n### 문제\n\n두 정수 `a`와 `b`가 주어졌을 때, `a`와 `b`의 합을 반환하시오.\n\n### 조건\n\n- -10⁵ < `a` < 10⁵\n- -10⁵ < `b` < 10⁵\n\n",
"solutionCode": "function solution(a, b) {\n  // a: 정수\n  // b: 정수\n  return 0;\n}", …
```
=> [#122] 대회 문제 조회 응답시 공개된 테스트케이스 값 보내주기

be/algo-with-me-api/src/competition/competition.module.ts, be/algo-with-me-api/src/competition/gateways/competition.gateway.ts, be/algo-with-me-api/src/competition/services/competition.service.ts, be/algo-with-me-api/src/dashboard/dashboard.gateway.ts, be/algo-with-me-api/src/dashboard/dashboard.module.ts, be/algo-with-me-api/src/user/services/user.service.ts
competition websocket 첫 연결시 검증
- 유저가 대회에 참여중인지 확인
- 동일한 유저의 다른 연결이 있을 경우 이전의 연결을 모두 끊음
- 이미 종료된 대회일 경우 연결을 끊음
competition websocket 제출 검증
- 대회시간 범위 안이 맞는지 확인, 아닐 경우 연결 끊음
클라이언트 유저 정보를 메모리(`client.data`)에 저장할지, 제출할 때 마다 db에서 가져올지 고민했습니다.
둘이 눈에 띌 만큼 큰 차이는 없다고 생각해서 db에서 가져오도록 했습니다. 추후 속도가 느려진다고 판단되면 메모리 저장으로 변경하겠습니다.
dashboard websocket 첫 연결시 검증
- 대회가 존재하는지, 대회 종료시간 이전인지 확인
https://www.notion.so/websocket-a122aa7e7ad64fac94f82b5ba9403551?pvs=4
=> [#186] websocket 검증로직 구현

frontend/panda.config.ts, frontend/src/components/Auth/AuthContext.ts, frontend/src/components/Common/BreadCrumb.tsx, frontend/src/components/Common/HStack/HStack.tsx, frontend/src/components/Common/HStack/index.ts, frontend/src/components/Common/Icon.tsx, frontend/src/components/Common/Logo.tsx, frontend/src/components/Common/VStack/VStack.tsx, frontend/src/components/Common/VStack/index.ts, frontend/src/components/Common/index.ts, frontend/src/components/Competition/CompetitionHeader.tsx, frontend/src/components/Competition/CompetitionProblemSelector.tsx, frontend/src/components/Editor/Editor.tsx, frontend/src/components/Header/index.tsx, frontend/src/components/Problem/ProblemHeader.tsx, frontend/src/components/Problem/ProblemSolveContainer.tsx, frontend/src/components/Simulation/SimulationResultList.tsx, frontend/src/components/Submission/SubmissionButton.tsx, frontend/src/hooks/editor/useUserCode.ts, frontend/src/pages/CompetitionPage.tsx, frontend/src/utils/type/__tests__/isNumber.ts, frontend/src/utils/type/index.ts
대회 화면 레이아웃 개선
테스트 케이스 추가 모달은 변경하지 않았습니다. 이 부분은 실제 테스트 케이스를 넣어 동작하게 되면 작업할 예정
테스트 결과 화면과 제출 결과 화면 분리도 구현하지 않았습니다. 이 PR이 너무 커져서 다음 테스크로 진행할 예정입니다.
https://github.com/boostcampwm2023/web12-algo-with-me/assets/40891497/44d7e1ef-15f4-4169-85e1-7d1fa42cf113
문제 이동, 코드 입력, 테스트 실행 등이 동작함을 확인할 수 있음
=> [#175] 대회 페이지 레이아웃 개선

be/algo-with-me-api/src/dashboard/dashboard.controller.ts, be/algo-with-me-api/src/dashboard/dashboard.service.ts
대시보드 조회할 때 mget으로 redis에서 유저들의 문제풀이 현황을 가져오는데, 매개변수로 들어가는 배열이 비어있을 경우 에러가 터져 서버가 멈춰버리는 문제가 있었습니다.
```javascript
const problems = await this.redis.mget(emails);
```
emails가 비어있을 경우 조기 리턴해주는 로직을 추가했습니다.
https://www.notion.so/39f47ac3813f4bc79b825cb07d43d12d?pvs=4
=> [#211] 대시보드 조회시 서버 죽는 문제 해결

be/algo-with-me-api/src/dashboard/dashboard.gateway.ts
대시보드 조회시 종료된 대회면 에러를 터트리고 소켓 연결을 끊는 로직이 있는데, await을 걸어주지 않아 여기에서 에러가 터져도 잡지 못하는 문제가 발생했습니다. 이로인해 서버가 그냥 아무 응답없이 죽어버렸습니다. 문제 해결을 위해 await, async를 걸어줬더니 잘 동작함을 확인할 수 있었습니다.
https://www.notion.so/39f47ac3813f4bc79b825cb07d43d12d?pvs=4
=> [#211] 비동기라서 throw error 안되는 문제 해결

be/docker-compose.yaml
- 로깅 파일이 저장 안되는 문제가 있었습니다. 확인해보니 도커 내부에만 저장되고 있어 호스트와 공유하도록 하였습니다.
- 도커의 시간이 UTC 기준으로 되어있어 한국시간으로 수정했습니다.
https://www.notion.so/f374f7b414c54c10a62314aa024002fa?pvs=4
=> [#202] 도커 로깅 폴더 공유, 도커 시간 한국시간으로 변경

frontend/src/apis/problems/types.ts, frontend/src/components/Problem/ProblemSolveContainer.tsx, frontend/src/components/Simulation/SimulationResultList.tsx, frontend/src/components/SocketTimer/index.tsx, frontend/src/hooks/problem/useCompetitionProblem.ts, frontend/src/hooks/simulation/types.ts, frontend/src/hooks/timer/useSocketTimer.ts, frontend/src/pages/CompetitionPage.tsx
- 서버에서 받은 테스트 케이스 타입 지정
- 서버에서 받은 테스트 케이스를  시뮬레이션 input 타입으로 변경
- 테스트 결과창에 예상 값 추가
https://github.com/boostcampwm2023/web12-algo-with-me/assets/78193416/0499ef7e-26d3-42c0-a18f-5bf86a6cad71
- https://www.notion.so/434b7c29f1f94f30b342f075843aa7e9?pvs=4
웹 소켓 연결도 해버렸습니다. pr 나누고 싶지만, 내일 데모해야하니..
https://github.com/boostcampwm2023/web12-algo-with-me/assets/78193416/14c01e0b-1809-41bf-a481-257f4baec502
=> [#183] 서버에서 받은 테스트 케이스 관련 작업

frontend/src/components/CompetitionDetail/BeforeCompetition.tsx, frontend/src/components/CompetitionDetail/Buttons/JoinCompetitionButton.tsx, frontend/src/components/Main/Buttons/JoinCompetitionButton.tsx
- 기존에 window.location.reload()코드를 navigate()로 바꿨습니다.
- 대회 참여는 대회 상세 정보 보기 페이지에서만 해서 버튼 컴포넌트의 위치를 바꿨고, navigate의 경로는 대회 상세 정보 보기 페이지로 작성했습니다.
netlyfi 임시 배포 페이지에서 실행했습니다.
=> [#226] 대회 참여 신청 후 페이지 에러

frontend/src/components/Problem/ProblemSolveContainer.tsx, frontend/src/hooks/simulation/useSimulation.ts
테스트케이스가 다른 탭을 갔다 오면 사라지는 버그 수정
*이 방식은 임시적인 방법입니다. 메모리에 테스트케이스가 그대로 남아있어 한 페이지를 계속 켜놓고 다른 여러 대회를 하면 할 수록 메모리를 먹게 됩니다. 시간상의 문제로 임시 해결 했음을 알립니다.
추가 후 다른 탭을 이동했다 와도 테스트케이스가 남아 있음
=> [#227] 테스트케이스가 다른 탭을 갔다 오면 사라지는 버그

frontend/src/components/UserValidator/index.tsx, frontend/src/pages/CompetitionPage.tsx
- websocket 관련 모든 error는 message event로 전달됨.
- 대회 페이지에서 message event가 오면 문제가 발생한 경우라 main 페이지로 이동해서 다시 검증하도록함.
- 한 사용자가 하나의 대회에 여러 탭에서 참여했을 때도 마찬가지로 message로 event가 오기 때문에 똑같이 메인 페이지로 이동하게 함.
- 소켓을 프로파이버로 사용하고 있어서 어느 컴포넌트에서 이러한 작업을 할까 고민하다 적절한 도메인이 없어서
- <></>를 반환하는 컴포넌트안에 해당 로직을 넣었는데 어떻게 생각하시나요?
- 시간 끝나면 대시보드 페이지로 네비게이션 하던 것도 main 페이지로 일단 바꿨습니다. 집계 후에 나오니까.
https://github.com/boostcampwm2023/web12-algo-with-me/assets/78193416/1e171850-1045-4e30-8da6-e2683bfacf7a
=> [#228] 대회 페이지 내에서 검증 실패가 되면 메인 페이지로 이동

be/algo-with-me-api/src/competition/controllers/competition.controller.ts, be/algo-with-me-api/src/competition/dto/competition.simple-response.dto.ts, be/algo-with-me-api/src/competition/dto/score-result.dto.ts, be/algo-with-me-api/src/competition/services/competition.service.ts
- 참여 가능 인원보다 많은 인원이 참여 되는 문제 수정
- 대회 생성 후 생성된 대회 정보 반환하도록 수정
- 클라이언트에게 보내주는 제출 결과에 stderr, memoryUsage, timeUsage 추가
- stderr, stdout 은 출력이 매우 길어질 수 있기 때문에 db에 저장하지 않습니다.
- 대회 메인 페이지에서 진행중, 그렇지 않은 대회 정렬
- 진행중인 대회는 상위 노출, 그렇지 않은 대회는 진행중인 대회 아래에 나오게 수정했습니다.
- 기본 정렬 기준은 "대회 시작일" 입니다.
- 대회 목록, 대회 상세 api 응답에 참여중인 인원, 최대 참여 가능 인원 추가
- 대회 상세엔 참가자 정보가 배열로 전달 되기 때문에 참여중인 인원을 따로 추가하지 않았습니다.
- 대회 목록에는 참여중인 인원을 추가하였습니다.
https://www.notion.so/1-b16be0fbc3584d76a48081a92204ca20?pvs=4
=> [#236] 1차 데모 이후 발생한 문제 수정

be/algo-with-me-score/Dockerfile, be/algo-with-me-score/src/main.ts, be/algo-with-me-score/src/score/services/fetch.service.ts, be/docker-compose.yaml
채점서버 개수 2개로 늘린 뒤 테스트했고 잘 동작하는 것 확인했습니다.
채점서버는 각각이 PromisePool을 가지고 있어, 도커서버에 일을 준 채점서버에서만 그 도커의 일이 끝났는지 확인할 수 있습니다.
그러므로 채점서버와 별도로 동작하며 도커서버 풀을 관리할 개체가 없다면, 도커서버들이 각 채점서버에 귀속되도록 해야 합니다.
간단히 나타내면 다음과 같은데, (괄호 안은 포트번호)
채점1 (4000) . . . . . . . . . . . . . . . . . . . . . . . . | 채점2 (4001) . . . . . . . . . . . . . . . . . . . . . . . . . 
도커1 도커2 도커3 도커4 도커5 (5000-5004) | 도커6 도커7 도커8 도커9 도커10 (5005-5009)
문제는 채점서버가 본인이 사용할 수 있는 도커가 무엇인지 알 수 없다는 것입니다. 즉 본인이 5000-5004 포트의 도커를 사용할 수 있을지, 5005-5009번 포트의 도커를 사용할 수 있을지 모릅니다.
포트번호 4000, 4001을 통해 알 수 있지 않느냐고 한다면 가능하지만(5000 + <자신의 포트> - 4000 * 5 ~), 안쪽의 채점서버는 자신이 바깥에 몇 번 포트로 드러나있는지 스스로 알 수 있는 방법이 없습니다.
https://stackoverflow.com/questions/39770712/how-can-a-container-identify-which-container-it-is-in-a-set-of-a-scaled-docker-c …
=> [#235] 채점서버 개수 늘리기

frontend/src/components/Competition/CompetitionHeader.tsx, frontend/src/components/Problem/ProblemSolveContainer.tsx, frontend/src/components/Submission/Score.tsx, frontend/src/components/Submission/types.ts, frontend/src/main.tsx, frontend/src/utils/unit/__tests__/byteToKb.spec.ts, frontend/src/utils/unit/index.ts
- 제출 결과 시간 및 메모리 사용량 출력
- 메모리는 KB, 시간은 1000으로 나눈 값을 출력 
- 소켓 이벤트로 problemResult 이벤트를 받아 결과를 알려줌
- 기존에 맞은 수를 카운트 하여 맞았다고 알려주는 로직은 제거
- 버그 픽스: 원소들이 아래 이미지처럼 정렬되는 버그 수정
- 이유는 VStack에 alignItems를 flexStart를 default로 설정하면서 설정이 없는 원소들이 다르게 동작하는 문제였음
맥북 에어 화면에서 깨지네요 홀홀
웹소켓 API 변경사항 확인하세요
https://www.notion.so/websocket-8ab0814b081a4f57994818de4c3b9a68?pvs=4
=> [#272] 제출 결과 시간 및 메모리 사용량 출력

frontend/src/components/Dashboard/DashboardLoading.tsx, frontend/src/pages/DashboardPage.tsx
대시보드 집계페이지에서 남은시간이 출력되지 않던 걸 수정했습니다.
=> [#274] 대시보드 집계페이지 남은시간
